name: test
main: tsp.invlib.test.Test
version: 1
api-version: 1.20
softdepend: ["PlaceholderAPI"]

commands:
  warps:
    usage: "/..."
  a:
    usage: "/.."
  matshop:
    usage: "/."
  canvas:
    usage: "/...."
  anim:
    usage: "/-"